
import type { Metadata, } from "next";
import LeftBar from "./leftbar";
import { Geist } from "next/font/google";
//import { Roboto } from 'next/font/google'
import Providers from "./providers"; 
import './globals.css';
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/*
const dictionaries = {
  en: () => import('./dictionaries/en.json').then((module) => module.default),
  fr: () => import('./dictionaries/fr.json').then((module) => module.default),
}
const roboto = Roboto({
  weight: '300',
  subsets: ['latin'],
})*/
const geist = Geist({
  weight: ['400'], 
  subsets: ['latin'],    
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Geist+Mono&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={`${geist.className} 100`} >

        <div className="flex mb-4">
          <LeftBar />

          <main className="w-7/8 bg-white-400 h-12 mt-2 p-2" >
          <Providers>{children}</Providers>
    
          
          </main>
        </div>
      </body>
    </html>
  );
}
